### ISSUE TITLE
'start offer' etc. in adDescription anpassen

### ISSUE THREAD

**Issue by doutzi** [scg-unibe-ch/ese2016-team4#17]
To-Do:
- start offer / price of sale
- sobald jemand geboten hat, darf 'Start offer' nicht mehr verändert werden

**Comment by kevin-meister** [comment]
What still needs to be done:

- index page displays only the initial bid, but not the highest
- owner of the auction can still bid
- people can overbid themselves
- your highest bid doesn't get displayed
