### ISSUE TITLE
release 2.0 bug report: search error

### ISSUE THREAD

**Issue by GretarGeiser** [scg-unibe-ch/ese2016-team4#32]
If you search for an add you either find nothing or get an http error 500
(I guess your search function was not yet complete when you pushed release 2.0)

(java.lang.NullPointerException
at ch.unibe.ese.team1.controller.service.AdService.validateDate(AdService.java:453)
at ch.unibe.ese.team1.controller.service.AdService.queryResults(AdService.java:320)
at ch.unibe.ese.team1.controller.SearchController.results(SearchController.java:49)
)

**Comment by kevin-meister** [comment]
Hi
The searchfunction seems to work for me on release 2.0
What were your inputs to reproduce the error? 
Did you use any special browser?
Also the nullPointerException seems strange, because the search should still work even if you search for an invalid date (e.g. "1234")

**Comment by GretarGeiser** [comment]
I used Firefox
I just tested everything again and it worked fine, until I tried to put in a latest move in date (a valid one, an invalid one workes just fine). Then it crashed and spit aout the nullpointer exception.
Since I was used to always set a latest move in date in our version I only just found the thing that crashes your search.

**Comment by kevin-meister** [comment]
search dates have been fixed
