### ISSUE TITLE
release 2.0 bug report: place-Ad bug

### ISSUE THREAD

**Issue by GretarGeiser** [scg-unibe-ch/ese2016-team4#35]
You want to make a new Ad with sale type auction or buy.
If you make a mistake on your place-Ad form (for example have a negative square meters value) it sets the input boxes back to rent.
This means you can now make inputs on price per month, move-in date and move-out date. But it still saves the form as an auction or a buy.

![placead1](https://cloud.githubusercontent.com/assets/22395484/20311502/50f7ee62-ab50-11e6-8792-527d6c0289d3.JPG)

![placead2](https://cloud.githubusercontent.com/assets/22395484/20311557/8a598db4-ab50-11e6-86c5-ecee5d3e9d9b.JPG)

**Comment by kevin-meister** [comment]
Fixed: displays the correct fields onload and onchange
