### ISSUE TITLE
release 2.0 bug report: edit-Ad bug

### ISSUE THREAD

**Issue by GretarGeiser** [scg-unibe-ch/ese2016-team4#36]
if you want to edit an existing ad bu make a mistake (for example a negative square meters value)
you can no longer change any general info apart from the title

![editad1](https://cloud.githubusercontent.com/assets/22395484/20311707/09e07fb6-ab51-11e6-8805-fd4d8307d0f0.JPG)

![editad2](https://cloud.githubusercontent.com/assets/22395484/20311711/0dcfb6c8-ab51-11e6-96de-0560363337c0.JPG)

**Comment by doutzi** [comment]
Possible solution: add this in the EditAdController - 
model = new ModelAndView("redirect:/profile/editAd?id=" + ad.getId());

Every time the form has errors, you are redirected to the same site (so the form stays the same). Problem: no warning will be displayed if there is an error.
