### ISSUE TITLE
release 2.0 bug report: Bid below starting bid

### ISSUE THREAD

**Issue by Maxasi** [scg-unibe-ch/ese2016-team4#37]
When being the first actual bidder of an auction, it is possible to bid less than the starting bid. This will then be shown as the current highest bid, yet the next bid starts off at the starting bid again (as shown in the picture attached).
The bug can be reproduced simply by making the first bid on an auction if it is below the starting bid.
![lower bid than starting bid](https://cloud.githubusercontent.com/assets/22397039/20314565/eb4a2566-ab5a-11e6-8db6-698221f2ff63.PNG)

**Comment by kevin-meister** [comment]
fixed, shouldn't be possible anymore
