### ISSUE TITLE
release 2.0 bug report: Overbidding yourself

### ISSUE THREAD

**Issue by Maxasi** [scg-unibe-ch/ese2016-team4#38]
It is not possible to overbid yourself (but we didn't know if that was intended like this). Anyway, if it's supposed to work: If you make a bid with a profile, you cannot make another higher bid as long as it's not raised by another profile. So, if John Wayne bids 150, an tries to raise his own bid to 180, it results in staying at 150. However, it works to go up to 180 as Jane Doe.

**Comment by kevin-meister** [comment]
This is working as intended
